name: Go

on:
  push:
    branches: [ "url-array-input" ]
  pull_request:
    branches: [ "url-array-input" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Tidy
      run: go mod tidy
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: ./go-clic https://www.elperiodic.com/
